### ISSUE TITLE
String index out of range: 11

### ISSUE THREAD

**Issue by Taebu** [Taebu/safen_cdr#2]
Aug 26, 2016 10:50:28 AM kr.co.cashq.safen_cdr.Safen_cmd_queue doMainProcess
WARNING: String index out of range: 11
Aug 26, 2016 10:50:28 AM kr.co.cashq.safen_cdr.Safen_cmd_queue doMainProcess
WARNING: java.lang.StringIndexOutOfBoundsException: String index out of range: 11
    at java.lang.String.substring(String.java:1907)
    at kr.co.cashq.safen_cdr.Safen_cmd_queue.is_freedailypt(Safen_cmd_queue.java:1194)
    at kr.co.cashq.safen_cdr.Safen_cmd_queue.doMainProcess(Safen_cmd_queue.java:221)
    at kr.co.cashq.safen_cdr.SAFEN_CDR.doWork(SAFEN_CDR.java:238)
    at kr.co.cashq.safen_cdr.SAFEN_CDR.doMainProcess(SAFEN_CDR.java:78)
    at kr.co.cashq.safen_cdr.SAFEN_CDR.main(SAFEN_CDR.java:39)

``` java

    private static boolean is_freeuserpt(String ed_type){
        boolean retVal=false;

        retVal = ed_type.substring(0,10).equals("freeuserpt");

        return retVal;
    }
```

**Comment by Taebu** [comment]
``` java


    private static boolean is_freeuserpt(String ed_type){
        boolean retVal=false;

        //System.out.println("ed_type.length() : "+ed_type.length());
        if(ed_type.length()>=10){
        retVal = ed_type.substring(0,10).equals("freeuserpt");
        }
        return retVal;
    }
```
