### ISSUE TITLE
java.sql.SQLException: Can not issue data manipulation statements with executeQuery().

### ISSUE THREAD

**Issue by Taebu** [Taebu/safen_cdr#3]
Aug 26, 2016 2:58:54 PM kr.co.cashq.safen_cdr.Safen_cmd_queue set_user_event_dt
WARNING: java.sql.SQLException: Can not issue data manipulation statements with executeQuery().
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:872)
    at com.mysql.jdbc.StatementImpl.checkForDml(StatementImpl.java:472)
    at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1976)
    at kr.co.cashq.safen_cdr.Safen_cmd_queue.set_user_event_dt(Safen_cmd_queue.java:1353)
    at kr.co.cashq.safen_cdr.Safen_cmd_queue.doMainProcess(Safen_cmd_queue.java:237)
    at kr.co.cashq.safen_cdr.SAFEN_CDR.doWork(SAFEN_CDR.java:238)
    at kr.co.cashq.safen_cdr.SAFEN_CDR.doMainProcess(SAFEN_CDR.java:78)
    at kr.co.cashq.safen_cdr.SAFEN_CDR.main(SAFEN_CDR.java:39)

``` java
            dao.openPstmt(sb.toString());

            dao.pstmt().setString(1, biz_code);
            dao.pstmt().setString(2, mb_hp);
            dao.pstmt().setString(3, daily_st_dt);
            dao.pstmt().setString(4, daily_ed_dt);
            dao.pstmt().setString(5, eventcode);

            dao.pstmt().executeQuery();
```

**Comment by Taebu** [comment]
``` java
            dao.openPstmt(sb.toString());

            dao.pstmt().setString(1, biz_code);
            dao.pstmt().setString(2, mb_hp);
            dao.pstmt().setString(3, daily_st_dt);
            dao.pstmt().setString(4, daily_ed_dt);
            dao.pstmt().setString(5, eventcode);

            dao.pstmt().executeQuery();
```
